# Base image (Airflow, Python script 등 추천)
FROM python:3.10-slim

WORKDIR /app

# Install OS dependencies if needed
# RUN apt-get update && apt-get install -y --no-install-recommends gcc main-utils

# Install Python dependencies
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
# COPY . .

# Run data pipeline script / Cron / Scheduler
# CMD ["python", "main.py"]
